version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: crunch_test
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: crunch_test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
